export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const ADD_TO_BURGER = 'ADD_TO_BURGER';
export const REMOVE_FROM_BURGER = 'REMOVE_FROM_BURGER';
export const SHOW_INGREDIENT = 'SHOW_INGREDIENT';
export const HIDE_INGREDIENT = 'HIDE_INGREDIENT';
export const CREATE_ORDER = 'CREATE_ORDER';
